services:
  web-service:
    container_name:  web-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "/app/prestart.sh"
    volumes:
      - ./web_server/app:/app/app
    ports:
      - 6007:6007
