services:
  web-service:
    container_name:  web-server-cuda
    image: namhoc123/cuda-whisper:1.3
    env_file:
      - .env
    command: "/app/prestart.sh"
    volumes:
      - ./web_server/app:/app/app
    ports:
      - 6007:6007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]