services:
  web-service:
    container_name: web-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "/app/prestart.sh"
    volumes:
      - ./web_server/app:/app/app
    ports:
      - 6007:6007

  web-service-translate:
    container_name: web-server-translate
    build:
      context: ./web_server_translate
      dockerfile: Dockerfile-fjs
    env_file:
      - .env-translate
    command: "/app/prestart.sh"
    volumes:
      - ./web_server_translate/app:/app/app
    ports:
      - 6008:6008

  triton-server:
    image: nvcr.io/nvidia/tritonserver:23.10-py3
    container_name: ai-platform-triton-server
    volumes:
      - ./triton_server/models:/models
    command: "tritonserver --model-repository=/models"
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002