# Use an official NVIDIA CUDA runtime as a parent image
# FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04
# FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
#FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
FROM nvidia/cuda:11.8.0-base-ubuntu20.04



WORKDIR /app

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y software-properties-common && \
    DEBIAN_FRONTEND=noninteractive add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get install -y python3.10 curl && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

RUN curl -sSL https://install.python-poetry.org | python3.10 - --preview
RUN pip3 install --upgrade requests
RUN ln -fs /usr/bin/python3.10 /usr/bin/python


#COPY ./web_server_translate/requirement.txt /tmp/requirement.txt
#
#RUN pip install --upgrade pip
#RUN pip install -r /tmp/requirement.txt --no-cache-dir