services:
  web-service:
    container_name:  web-server-cuda
    image: cuda-whisper:1.0
    env_file:
      - .env
    command: "/app/prestart.sh"
    volumes:
      - ./web_server/app:/app/app
    ports:
      - 6007:6007
